package Interface;

import EDD.Global;
import EDD.GrafoMA;
import javax.swing.JOptionPane;

public class AddOrDeleteCity extends javax.swing.JFrame {
    
    private GrafoMA grafo = Global.getGrafo();
    
    public AddOrDeleteCity() {
        initComponents();
        this.setVisible(false);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEliminarVertice = new javax.swing.JButton();
        ciudadEliminar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnAgregarVertice = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAristas = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(380, 635));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEliminarVertice.setFont(new java.awt.Font("Aspekta", 0, 13)); // NOI18N
        btnEliminarVertice.setForeground(new java.awt.Color(102, 102, 102));
        btnEliminarVertice.setText("ELIMINAR");
        btnEliminarVertice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarVerticeActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminarVertice, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 520, 100, -1));
        getContentPane().add(ciudadEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 490, 40, 20));

        jLabel3.setFont(new java.awt.Font("Aspekta", 2, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("DE LA CIUDAD:");
        jLabel3.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, 180, -1));

        jLabel4.setFont(new java.awt.Font("Aspekta", 2, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("INGRESE EL NÚMERO");
        jLabel4.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, 160, -1));

        btnAgregarVertice.setFont(new java.awt.Font("Aspekta", 0, 13)); // NOI18N
        btnAgregarVertice.setForeground(new java.awt.Color(102, 102, 102));
        btnAgregarVertice.setText("AGREGAR");
        btnAgregarVertice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarVerticeActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarVertice, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, -1, -1));

        txtAristas.setColumns(20);
        txtAristas.setRows(5);
        jScrollPane2.setViewportView(txtAristas);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, 100));

        jLabel5.setFont(new java.awt.Font("Aspekta", 2, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("DEBE HACER UN SALTO DE LÍNEA!");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 190, 20));

        jLabel6.setFont(new java.awt.Font("Aspekta", 2, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("INDIQUE LAS CONEXIONES CON OTRAS");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 300, 30));

        jLabel7.setFont(new java.awt.Font("Aspekta", 2, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 102, 102));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("\"Ciudad destino, Ponderación.\"");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 220, 30));

        jLabel8.setFont(new java.awt.Font("Aspekta", 2, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("CIUDADES EN EL SIGUIENTE FORMATO:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 300, 30));

        jLabel9.setFont(new java.awt.Font("Aspekta", 2, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("EN CASO DE EXISTIR MÁS DE UNA CONEXIÓN");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 260, 20));

        jLabel1.setFont(new java.awt.Font("Aspekta", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("AGREGAR CIUDAD");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 250, -1));

        jLabel2.setFont(new java.awt.Font("Aspekta", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ELIMINAR CIUDAD");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 240, -1));

        jButton1.setFont(new java.awt.Font("Aspekta", 0, 13)); // NOI18N
        jButton1.setText("LISTO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 590, 80, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarVerticeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarVerticeActionPerformed
        grafo.deleteVertex(Integer.parseInt(ciudadEliminar.getText()) - 1);
    }//GEN-LAST:event_btnEliminarVerticeActionPerformed

    private void btnAgregarVerticeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarVerticeActionPerformed
        if(!"".equals(txtAristas.getText())){
            grafo.insertVertex(1);
            String aristas = txtAristas.getText();
            String[] aristasArray = aristas.split("\n");
            for (int i = 0; i < aristasArray.length; i++) {
                String[] arista = aristasArray[i].split(",");
                grafo.insertEdge(grafo.getNumVertex()-1,Integer.parseInt(arista[0]) - 1, Double.parseDouble(arista[1]));
            }
            txtAristas.setText("");
        }else{
            JOptionPane.showMessageDialog(null, "Debe llenar la información de las aristas");
        }
    }//GEN-LAST:event_btnAgregarVerticeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Homescreen v1 = new Homescreen();
        this.setVisible(false);
        v1.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddOrDeleteCity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddOrDeleteCity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddOrDeleteCity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddOrDeleteCity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddOrDeleteCity().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarVertice;
    private javax.swing.JButton btnEliminarVertice;
    private javax.swing.JTextField ciudadEliminar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtAristas;
    // End of variables declaration//GEN-END:variables
}
